### ISSUE TITLE
インデントの統一

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#23]
インデントがバラバラすぎる。

HTML: 2space
CSS/JavaScript: 4space

に統一する。

**Comment by yumetodo** [comment]
#25 でHTMLについては統一した。

**Comment by akihikodaki** [comment]
CSS/JavaScriptも2 spacesでいいじゃないか.

**Comment by yumetodo** [comment]
まあいいですが。何れにせよ統一してlintで強制するべきという認識。

**Comment by akihikodaki** [comment]
以下のcommitsで解決。
594ae3bc471138107bf07ea5c60525c0574ede66
52046bfe130431f89f67f9f7d911af20e5d519ee
