### ISSUE TITLE
HTMLHint/CSSLint/ESLintの適応

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#24]
[JavaScript、HTML、CSSを簡単にLintできる開発環境を作った - Qiita](http://qiita.com/muraken720/items/468b9f420ab4c900e241#htmlhintrc)

**Comment by yumetodo** [comment]
合わせて
#23 もどうにかする。

**Comment by yumetodo** [comment]
https://github.com/CSSLint/csslint/wiki/rules

**Comment by akihikodaki** [comment]
以下のcommitsで解決。
594ae3bc471138107bf07ea5c60525c0574ede66
52046bfe130431f89f67f9f7d911af20e5d519ee
