### ISSUE TITLE
1703: 広報課からのバグレポ

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#30]
1. [/index.html](http://miraiken.github.io/web/event/2017/event_march/index.html): 上部に「2016年も開催決定」とある
2. [/index.html](http://miraiken.github.io/web/event/2017/event_march/index.html): 日時に曜日も追加
3. [/index.html](http://miraiken.github.io/web/event/2017/event_march/index.html): 駐輪スペースについて追記
4. [/access.html](http://miraiken.github.io/web/event/2017/event_march/access.html): バスの情報追加
5. [/access.html](http://miraiken.github.io/web/event/2017/event_march/access.html): 駐輪スペースについて記載
6. [./exhibition.html](http://miraiken.github.io/web/event/2017/event_march/exhibition.html): はよ！

**Comment by yumetodo** [comment]
1-> げげっ、普通に直し忘れてた

3-> **Reject.** 広報課の皆様方はイベント**概要**という言葉を見落としているのであろう。

4-> **Reject.** 広報課の皆様方は会場が駅前だということを忘れているのであろう。つまりバスが必要なのは地元民のみ。**一体誰に向けた情報なのか？** プログラミングの大原則、**Keep it simple, stupid** に反する。

5-> @NishiCell チラシに書いたこと #とは

**Comment by yumetodo** [comment]
@NishiCell 何れにせよ、 #29 をmergeしないことには作業できない。さもなくばconflictの嵐に見舞われるであろう。

**Comment by celluloce** [comment]
チラシに書いたことについて
詐欺広k…ゲフンよく見る広告のように
左下に小さく書かれています。

**Comment by yumetodo** [comment]
学校配布ビラ突っ込みどころ多いなぁ・・・。もう言わないでおくけど。当日ビラについては・・・うん、去年と同じ指摘だからこれも言うまい。

>※駐輪スペースに限りがあり、自転車の駐輪をお断りすることがあります。
>- 徒歩
>- 電車
>- バス
>
>でお越しください。

これのこと・・・？

---

あー、バスの件、学校配布ビラには書いているのか・・・。書いた人は一体何をかんが・・・ゲフンゲフン、書かざるをえないか・・・。

**Comment by yumetodo** [comment]
#32 にて上記のうち1,2,4,5は対処。
#31 #34  にて6については対処。

#32 margeし次第close
