### ISSUE TITLE
Webページリニューアルに向けて

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#43]
# Work flow

1. 現状のUI flowをまとめる -> #20 
2. 現状提供している情報が何かをまとめる
3. 現在のWebページの問題点をまとめる
4. 追加/削除するべき情報を議論・整理
5. UIフローを考える
6. 全ページに共通するデザインを決定
7. (必要なら)各ページのデザインの決定
8. すでにあるページの移行をするときの問題点の洗い出し
9. (必要なら)CI環境、サーバー構築
10. Webページ作成開始

**Comment by yumetodo** [comment]
ref:
- #82

**Comment by akihikodaki** [comment]
既に多くの変更が行われた。もはや大規模な変更は不要。
