### ISSUE TITLE
非サポート環境への警告文章の改善

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#45]
- https://miraiken.github.io/web/no_supported_browser.html
- https://miraiken.github.io/web/no_supported_browser-sjis.html

にて、未来研究室実行委員会でサポートしていない環境からの閲覧に対し警告を発している。

しかし、文章が硬いのではという @NishiCell の指摘があるので議論する。

ref
- #44

**Comment by yumetodo** [comment]
@NishiCell 
個人的にこの警告ページの意義は


- 古い環境をサポートするのは開発コストがかかる(Work Aroundが増える)
- めでたくVistaが死んだので、IE11以外のIEは殺すべきであるという全世界的な声への対処
- 古いAndroidには人権もセキュリティもないのでやはり殺すべきという全世界的な声への対処
- 古い環境をサポートすることは、利用者をセキュリティ的に危険に晒し、結果的に利用者のためにならない

=> 警告文が必要

だと思っています。「お知らせ」ではなく、「警告文」の体で書いているので当然文章はきつい表現になっています。

しかし

- 文章が硬くて、かえって何言ってるのかわからない
- 文章が冗長

という気もしています。

**Comment by yumetodo** [comment]
- なぜこのページに飛ばされたのか(Why?)
- どうするべきなのか(How?)

が分離していない感があるのはどうにかしたい

**Comment by celluloce** [comment]
現在Markdownを使って書き直していますが、どちらで公開しましょう？

**Comment by celluloce** [comment]
（正直、余計なお世話なのでは要素が多いですがそこは目を瞑りましょう）

**Comment by yumetodo** [comment]
んー、[gist](https://gist.github.com/)に書いて、リンク貼ってくれればええよ。

**Comment by celluloce** [comment]
まだ書き終えてない（警備員の理科大生狩り＆今日の気力が尽きた）のでまだ途中ですが。

**Comment by yumetodo** [comment]
書きかけでもcommit、それがgitだ。(gistもgitで管理できる、ディレクトリ作れないけど)

**Comment by celluloce** [comment]
https://gist.github.com/NishiCell/e7938646f68264a7782418c69a88f1e9
