### ISSUE TITLE
新入生ページの書き変え

### ISSUE THREAD

**Issue by celluloce** [miraiken/web#47]
WEBページ 新入生向けページの書き変え】

新入生向けページが去年のままである。
特に「今後の予定」は早急に書き換えなければいけない。

現在委員長に「今年度の今後の予定」を問い合わせ中。

**Comment by celluloce** [comment]
>返信遅くなって申し訳ない。
>新入生向けの今後の予定としては
>
>4/16（日）17:00〜説明会(神楽坂キャンパス844教室)
>4/16（日）18:00〜新入生歓迎食事会
>4/23（日）11:00〜東芝未来科学館見学
>4/23（日）12:00〜食事会
>
>です。
>問い合わせは
>2017sinkan.miraiken@gmail.com
>にお願いします。

早急に書き換える必要があるのでGPGなしでcommitします。

**Comment by yumetodo** [comment]
@NishiCell 了解

**Comment by yumetodo** [comment]
https://github.com/miraiken/web/pull/48#discussion_r111539045
というわけで早めに6月イベントまでのスケジュールを。

**Comment by celluloce** [comment]
>第5回部会連絡
>日時：5/14（日）16:00～
>場所：神楽坂キャンパス(教室未定)
>内容：イベント前最終確認等
>※同日同所13:00～6月期第3回団体代表者会議をやります。

とのことなので書き加えます。

**Comment by yumetodo** [comment]
@NishiCell 一応こっちにも6月イベントについて言及するべきじゃないかい？

**Comment by celluloce** [comment]
@yumetodo 
そうですね。
"今後の予定"にイベント当日の日程を追加 -> 新branchでcommit -> pullrequest
でおｋですか？

**Comment by celluloce** [comment]
ついでに5/14部会を行う教室がわかったので書き変えとく。

追記：残りの"未定"を全て空欄にする。

**Comment by celluloce** [comment]
pullrequest投げた：https://github.com/miraiken/web/pull/63

**Comment by yumetodo** [comment]
もう今季の新歓はおわっただろう。
