### ISSUE TITLE
Facebookへのリンクを貼り付ける

### ISSUE THREAD

**Issue by celluloce** [miraiken/web#66]
removed

**Comment by yumetodo** [comment]
あれ運用してるの？

**Comment by NishiCell** [comment]
>最近、はるかさんの力添えで公式Facebookのアカウントもできたから、それを言ってもいいも

**Comment by yumetodo** [comment]
はい！？と思って
https://www.facebook.com/miraiken.tus.0603/
見に行ったら、すげぇ久々に動いてるな・・・。

え、なに、これまともに運用する気なの？誰がどう運用するかで揉めて、これまで公式SNSの類はまともに運用されてなかったのに。
