### ISSUE TITLE
1706イベントページにパンフレット画像を貼り付ける

### ISSUE THREAD

**Issue by celluloce** [miraiken/web#67]
PDFファイルをPNGファイルに変換し、`/event/2017/event_june/index.html`に貼り付ける。

**Comment by NishiCell** [comment]
ちょっとまて、`.ia`拡張子って何なんだ？

**Comment by yumetodo** [comment]
PNGではなくsvgに

**Comment by yumetodo** [comment]
結局実施されなかったが、今更なのでcloseする。
