### ISSUE TITLE
ジェネレーター導入=>Pugる

### ISSUE THREAD

**Issue by akihikodaki** [miraiken/web#72]
`head`にsubresource integrityやContent Security Policyについて追記を行いたいが、ページ数が多く煩雑。ジェネレーターを導入すべき。要件は以下。
* ヘッダとフッタを含むテンプレートを適用する機能
* Webpack連携

**Comment by yumetodo** [comment]
>Webpack連携

絶対必要。

>ヘッダとフッタを含むテンプレートを適用する機能

というと

**Comment by akihikodaki** [comment]
> > ヘッダとフッタを含むテンプレートを適用する機能
>
> というと

例えば`html-loader`では他のファイルを含める指示は静的なので容易には実装できない。以下の`./content.html`の部分を複数のファイルに対して適用できる必要がある。
```HTML
<html>
    <head></head>
    <body>
      <main>${require("./content.html")}</main>
      <footer></footer>
    </body>
</html>
```

**Comment by yumetodo** [comment]
つーか、今HTML読み込んでいる(サイドバー)けどあれjsonからmithrilで動的構築するべきかなと思っている。Webpackでコンパイル時にHTML構築できるならそれでいいんだけど、「容易には実装できない」とかいう時点で敬遠したい。

**Comment by akihikodaki** [comment]
いや、`html-loader`が悪いのであってそれ以外の選択肢はある。例えばMithrilで静的構築も可能。

**Comment by yumetodo** [comment]
>例えばMithrilで静的構築も可能。

まじで・・・？

**Comment by akihikodaki** [comment]
https://github.com/MithrilJS/mithril-node-render
か
https://github.com/markdalgleish/static-site-generator-webpack-plugin

**Comment by yumetodo** [comment]
どちらもhtmlの加工に使えるようには見えないんだが(全部JSで生成するとかそれどこのJSX・・・)

**Comment by akihikodaki** [comment]
> (全部JSで生成するとかそれどこのJSX・・・)

良いじゃないか

**Comment by yumetodo** [comment]
純粋にメンテ可能性落ちません？

**Comment by akihikodaki** [comment]
そうでもないだろう。ただJSXにするかMithrilの記法を用いるかの問題はある。

**Comment by yumetodo** [comment]
JSXは好きではない。すでにMithrilは利用されているので馴染みが深い。

**Comment by akihikodaki** [comment]
JSXよりもMithrilのほうが馴染み深いって何かおかしくないか？

**Comment by yumetodo** [comment]
実際、動的構築にすでに使っているわけで。

**Comment by akihikodaki** [comment]
一応JSXをMithrilで使うやり方は以下に
https://mithril.js.org/jsx.html

**Comment by yumetodo** [comment]
知ってるけどMithrilの良さ死んでますやん

**Comment by akihikodaki** [comment]
そんなことはないと思うんだけど。

**Comment by yumetodo** [comment]
Mithril: ただのJavaScript
JSX: HTMLもどきが異世界転生して現代社会に現れたもの

**Comment by akihikodaki** [comment]
Riot.jsが良いかもしれない。

**Comment by yumetodo** [comment]
Riot.jsは動的に動かすには重いが、静的に使えるのかい？

**Comment by akihikodaki** [comment]
カスタムタグ · Riot.js
http://riotjs.com/ja/api/#%E3%83%AC%E3%83%B3%E3%83%80%E3%83%AA%E3%83%B3%E3%82%B0

これと先に挙げたstatic-site-generator-webpack-pluginと組み合わせればいける。

**Comment by yumetodo** [comment]
ほう。WebComponent的なものが静的に使えるのはいい。

**Comment by akihikodaki** [comment]
npmを"template"で検索してpopularityでソートした。
https://www.npmjs.com/search?q=template&ranking=popularity
ejsは要求に合う。
https://github.com/mde/ejs
これでいいかな。

**Comment by yumetodo** [comment]
実質開発者一人なんですが・・・

**Comment by akihikodaki** [comment]
HMRもできたら良いなあとは思うのだけどちょっと難しい。

**Comment by akihikodaki** [comment]
Webpackのloaderが公式で提供されているpugを使おう。これならwatchもできるし良いと思う。
https://github.com/pugjs/pug-loader

**Comment by yumetodo** [comment]
ますますよくわからないものが出てきた・・・

**Comment by akihikodaki** [comment]
Mithrilなんかより有名だ。

**Comment by yumetodo** [comment]
なるほど、Pugという言語があるんだな？
https://pugjs.org/language/includes.html

**Comment by akihikodaki** [comment]
とりあえず実装始めた。

**Comment by akihikodaki** [comment]
CSS scope使いたいけどJSXとかMithril使わないと無理。

**Comment by yumetodo** [comment]
あれってWeb Componentsに吸収されて死んだはずでは・・・

**Comment by akihikodaki** [comment]
CSS scopeというよりCSS moduleだ。

**Comment by yumetodo** [comment]
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

とか言われるんだがどのパケージが原因だ？

**Comment by akihikodaki** [comment]
a5d906b0364424ce59dcd5a1354a1f050d68f414 で解決。
