### ISSUE TITLE
copyrightの年号および更新日時の表示をどうするか

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#77]
copyrightの年号取得がぶっ壊れている。

#71 で取り上げたように、どのみち`document.lastModified`は使いものにならないので、gitのcommit logから日付を抽出するべきだ。 #72 にて、Pugるようになったことで、Github APIの利用も現実的ではない(deployのときに`gh-pages`を作り直すのをどうにかできるならGithub APIで十分だが)。

pugファイルをビルドするときに吐き出すhtmlごとに関連ファイルの更新日時の中で最も新しいものを抜き出すとかできないのか？

**Comment by yumetodo** [comment]
@akihikodaki つーかなんで`gh-pages`が毎回生成されるんだ？少なくとも今の`gh-pages`はこれまでの`gh-pages` ( https://github.com/miraiken/web/commit/339953af644446cf98693804e56595b7840dc28f )とは孤立している。

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/29278536-04016404-8150-11e7-9ea5-00d50a9f0c95.png)

**Comment by akihikodaki** [comment]
@yumetodo dpl gemを読んで

**Comment by yumetodo** [comment]
@akihikodaki #とは

**Comment by akihikodaki** [comment]
Travis CIが使ってるライブラリ

**Comment by yumetodo** [comment]
>https://github.com/travis-ci/dpl#github-pages
>target-branch: Branch to push force to, defaults to gh-pages.

ようはhttps://github.com/travis-ci/dpl にforce pushしない機能の要望を投げろと。

**Comment by yumetodo** [comment]
いや、たかが`gh-pages`へのデプロイくらいすぐにスクリプトかけるだろ。だいいち、Travis CIの出力を見ることができる視力があれば

>!!! GitHub Pages support is experimental !!!

という出力に気がつくはずだ、つまり使い物にならん。

**Comment by akihikodaki** [comment]
そのスクリプト書くぐらいならpugの出力に時刻埋め込む実装するわ。見た感じpugから普通に関数呼び出し (つまりNode.jsの関数を叩ける) ようだから、それでGitを叩けばいい。

**Comment by yumetodo** [comment]
ビルド重くね？と思ったが、初回以外はビルドキャッシュ効くか。しかしexperimentalなものを実戦投入とか怖さ。

**Comment by akihikodaki** [comment]
Node.js使ってる時点でパフォーマンス的には冗談みたいなものだ。Travis CIも自前でscriptを書いても生来も動く保証なんてないだろう。

**Comment by yumetodo** [comment]
https://github.com/miraiken/web/commit/f5c15e50f6a0e34342a51d3aad4bbc589a26b8e6 で埋め込もうとしているようだが、埋め込まれていない

**Comment by akihikodaki** [comment]
`update_date`を`load_parts`で読み込んでいたものが死んでいる。直す。

**Comment by yumetodo** [comment]
```pug
#{lastModified.toLocaleString("ja")}
```

を用いているが、これは期待する結果を得られない。

```pug
#{lastModified.getFullYear()}/#{date.getMonth() + 1}/#{date.getDate()} #{date.getHours()}時#{date.getMinutes()}分
```

とかとするべきではないか?

**Comment by akihikodaki** [comment]
何が問題?

**Comment by akihikodaki** [comment]
一応、`toLocaleString`に更にオプションを追加することでフォーマットは変更できるが、その必要はないと考えた。

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/29301722-3c3c93fc-81b9-11e7-9f27-611fe4ff2359.png)

一般的な日本人には馴染みのない表記。あとタイムゾーンおかしい。

**Comment by akihikodaki** [comment]
ローカルで見えるのと違う。ICUが入ってないか。

**Comment by yumetodo** [comment]
おおよそロケールなんてものが信用できるはずがない(C++er脳

**Comment by akihikodaki** [comment]
Travisが信用できないだけだ。何でもかんでもbetaだし開発環境のくせにバージョンが古ければディストリもUbuntuだけ。それでもよく使われてるだけ、四苦八苦すればとにかく使い物にはなる。

**Comment by yumetodo** [comment]
だからあれだけShippableを使えと・・・

**Comment by yumetodo** [comment]
あれ、でもdockerコンテナ使えなかったっけ？(過剰装備

**Comment by akihikodaki** [comment]
18dea487c00cc6a2c5f3e05bc1d7537da527075b で直るかと思ったけど直らない。私の環境と変わらないはずなのに。

**Comment by yumetodo** [comment]
`LC_ALL`いじればワンちゃん？

**Comment by akihikodaki** [comment]
`LANG`だけで変わることを確認している。

**Comment by akihikodaki** [comment]
LTSじゃなくて最新のNode.jsを使うことで解決した。手元だとLTSでも`LANG`で変更できたのに。謎。

**Comment by akihikodaki** [comment]
（タイムゾーンはこれから）

**Comment by akihikodaki** [comment]
61b1b4c576c04f23ca28d448c1bd568c64f4b9de でタイムゾーンも設定した。`getFullYear`の方は設定されていないが、まあ良いだろう。

**Comment by akihikodaki** [comment]
以下のcommitsで解決。
f5c15e50f6a0e34342a51d3aad4bbc589a26b8e6
efb6448490b8edb8475d7caced4b69c5c7bde320
b34eb898fcb5410c012935fd495af4ba95e698e5
61b1b4c576c04f23ca28d448c1bd568c64f4b9de
