### ISSUE TITLE
大体全部のhtmlが全部同じになっている。

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#78]
どういうことだってばよっ！？

**Comment by yumetodo** [comment]
#77 くらいならまあいいかと思ったが、さすがにこれは見逃せないので、一時的に #72 直前に差し戻しforce pushした。Travis CIによって作られた`gh-pages`は`gh-pages-rescue-201708160021jst`にリネームした。

**Comment by akihikodaki** [comment]
@yumetodo thx
extract-text-webpack-pluginにバグがあることを確認したので修正する。

**Comment by yumetodo** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin/pull/601
これか

**Comment by akihikodaki** [comment]
46dfdde7694f232115b1d57bea7c0505cca13194 で解決。
