### ISSUE TITLE
イベントページが死んでいる

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#79]
# 201706
## exhibition
- [x] `/event/2017/event_june/resource/js/exhibition_creater.js`がない  
=> 1835224966123a262c57b7b475730f5c7d2f6e18
- [x] `/event/2017/event_june/resource/js/exhibition_creater.js`内部で参照しているjsonが消えている  
=> 30da45479f1abcb639985bd877621c5139df45e3

# 201703
## exhibition
- [x] `/event/2017/event_june/resource/js/exhibition_creater.js`内部で参照しているjsonが消えている  
=> 30da45479f1abcb639985bd877621c5139df45e3
- [x] `Uncaught (in promise) Error` file not found
=> 30da45479f1abcb639985bd877621c5139df45e3

# 201606
## exhibition
- [ ] cssが死んでいる  
=> https://github.com/miraiken/web/commit/dfede7dec9f424e35bb24537845a17e9b4f8cdc0 , https://github.com/miraiken/web/commit/a1acc2dd5fe77c51cefed285dc8d65a25efa73e9
- [x] `/web/event/2016/event_june/resource/img/puzzle.png`がない  
=> https://github.com/miraiken/web/commit/277dd3b4bfd867bfe5fafc4597122ddd7472fd13

## nisokon
- ~~cssが死んでいる~~
## lecture
- [x] なぜかイベントページ以外共通のサイドバーが読み込まれている  
=> https://github.com/miraiken/web/commit/b29bf74c32f2765e22a52b01696fe96d7141d627
## workshop
- [x] なぜかイベントページ以外共通のサイドバーが読み込まれている  
=> https://github.com/miraiken/web/commit/b29bf74c32f2765e22a52b01696fe96d7141d627

# 201406
## exhibition
- [x] 幾つかのgifが読み込まれていない  
=> https://github.com/miraiken/web/commit/9bba66e98804005c15b26cbd94b4b781b527d7d2

**Comment by akihikodaki** [comment]
CSSが死んでいるとはどういうこと? 404も出てないし以前と表示は変わらないように見える。

**Comment by yumetodo** [comment]
>Failed to load resource: the server responded with a status of 404 () style.css 

と怒られている。

**Comment by yumetodo** [comment]
CSSおかしい件、これで治ったはず・・・

**Comment by yumetodo** [comment]
まだだった、今度こそ・・・

**Comment by yumetodo** [comment]
治ったっぽい。
