### ISSUE TITLE
redirect_when_no_supportを消したい

### ISSUE THREAD

**Issue by akihikodaki** [miraiken/web#80]
`redirect_when_no_support`は冗長で、かつ不十分な実装でも動作するようにしなければならず、メンテナンスも面倒。削除できるはず。
@yumetodo

**Comment by yumetodo** [comment]
せやろか?headタグ内に書くからblockingするという問題はあるが、非対応環境からのことを切り捨てるのはどうだろうか・・・

![Total Access](https://user-images.githubusercontent.com/10869046/29303404-871ffce8-81c7-11e7-9e86-52e37aae30ff.png)
Total Access
![Windows Internet Explorer Access](https://user-images.githubusercontent.com/10869046/29303180-d73aae78-81c5-11e7-9035-1b776f6299db.png)
Windows Internet Explorer Access
![chrome(mobile) access](https://user-images.githubusercontent.com/10869046/29303312-ea5382d6-81c6-11e7-8f05-18dc6fca67b4.png)
chrome(mobile) access
![safari(mobile/tablet access)](https://user-images.githubusercontent.com/10869046/29303370-3ffe30aa-81c7-11e7-8a32-44c1d7d7da08.png)
safari(mobile/tablet access)

どんぶり勘定で10%は古い環境からアクセスしている。

**Comment by yumetodo** [comment]
@akihikodaki 
Google Analyticsの解析権限渡そうか？

**Comment by akihikodaki** [comment]
数百程度のアクセスなんて気にしたら負けだろ。
権限欲しい。akihiko.odaki.4i@stu.hosei.ac.jpでいける?

**Comment by yumetodo** [comment]
>数百程度のアクセスなんて気にしたら負けだろ。

そもそも全体がそんなに多くねーよ。

---

とりあえず投げてみたが・・・。

**Comment by akihikodaki** [comment]
全体がどうだろうと数百は数百だ。サポートする必要ないと思うが。

**Comment by yumetodo** [comment]
まてやい、どう考えても割合で考えるべき事案では・・・

>不十分な実装でも動作するようにしなければならず、メンテナンスも面倒

とはいうが例えばどんなコストが維持した場合発生する?

**Comment by akihikodaki** [comment]
そもそもWebpackがまともに動いているかわからない。

**Comment by akihikodaki** [comment]
とりあえずこれ殺してからBabelを導入したいんだけど、どう?

**Comment by yumetodo** [comment]
まあわかった。
close #45

**Comment by akihikodaki** [comment]
#81 で解決。
