### ISSUE TITLE
Responsive Web Design

### ISSUE THREAD

**Issue by akihikodaki** [miraiken/web#82]

**Comment by yumetodo** [comment]
みらいけん広報班cybouzuで話してたこの辺の部分を抜き出しておく。

---

135: M.I. 2015/12/6(日) 15:32
質問なんですけど、
HPのデザインをするときにページ全体をデザインするのか（レイアウト含め）
このページのこのパーツ（例えばタイトルロゴの素材をくださいとか、各ページに飛ぶタブとか）を作るのかどっちをやればいいですかね？

136: yumetodo 2015/12/6(日) 17:07
>135 への返信
前者です。統一感のない配色をどうにかするのが第一目標ですので。緑を基調に。

今のところ思っているイメージ

![miraiken_design_concept_v001](https://user-images.githubusercontent.com/10869046/29621252-29d91ebc-885b-11e7-86ac-d97cfbb49786.png)

(雑なのは目をつぶってください)

- モバイル・PC両対応にする
- そのためにはパーツを「ブロック」として捉え、デザインはブロックの配置とブロック自体のデザインに分離する
- パーツを大きくしない
- 画像ファイルの使用を減らす(HTML5にはcanvasがあるのでその気になればかなり高度な描画も可能、というか頑張れば(嫌だけど)フォトショップを再現できる)

137: yumetodo 2016/1/7(木) 10:25
## とりあえず早めにほしい素材

hタグに使っている画像にかわるなにか。

![default](https://user-images.githubusercontent.com/10869046/29621495-dd01c1ce-885b-11e7-95ab-8c7eb99c57b0.png)

もうすこし自己主張しない、さわやかな？もの。
いっそ
http://chibilab.web.fc2.com/index.html
ちびラボみたいに○だけでいいのではないか説
 
## はやめに決めたいこと

- 緑の背景に白いボックスおいて黒字、か、白背景に緑のボックスか(緑色をもっと推すの決定事項)  
前者は >>136 で私が出した素案、後者は記憶があやふやだけどM.I.先輩の作ってたやつ・・・かな

**Comment by yumetodo** [comment]
という話をしていた。

まあ今思っていることとしては、例に上げたデザインは、画面幅狭い時に「メニュー」にまとめてしまうのはあんま良くないなと思っている。

**Comment by akihikodaki** [comment]
まずは今のままRWDを実装する。変わるのは画面が小さくなったときにパーツが上に行くか下に行くかだけだ。

**Comment by yumetodo** [comment]
いや、UIの問題点は、上にも右にも操作できるボタンがあって、操作が一定しないことだという認識

**Comment by akihikodaki** [comment]
その右にあるボタンが下に行くんだよ。

**Comment by yumetodo** [comment]
なお悪いじゃねーか

**Comment by akihikodaki** [comment]
Holy Grail Layoutっていって普通によくある。

**Comment by akihikodaki** [comment]
同じ場所にあることではなくてユーザーにとって必要なものが上に出ていることが重要。

**Comment by yumetodo** [comment]
- ホーム
- イベント情報
- お問い合わせ
- リンク
- 新入生向けページ

というボタンが横に並んでいるが、これだとボタンの数増やすときに困るんだよ。上の画像のデザインはそういうことの解決として広い時は横、そうでない時は上に持っていくFlexboxを作ろうというもの。

**Comment by akihikodaki** [comment]
それはボタンの数を増やすときにね。

**Comment by yumetodo** [comment]
だから上と右統合しません？という思い

**Comment by akihikodaki** [comment]
あー、なるほどね。でもそれらのボタンって表示されるべき優先度が違うでしょ。

**Comment by yumetodo** [comment]
そんなこともないと思う。

**Comment by akihikodaki** [comment]
5個以上もボタンがズラッと並んでいるのが利便性が高いと思う?

**Comment by yumetodo** [comment]
このさい、ボタンっぽさはある程度妥協するんだよ。Yahoo! Japanをみてみろ、フラットデザインとかが流行る前からこいつらフラットだぞ(違
![image](https://user-images.githubusercontent.com/10869046/29646044-f754389e-88bb-11e7-8906-ea765b3d13b2.png)

**Comment by akihikodaki** [comment]
それはあと。一気に全部やろうとしない。

**Comment by yumetodo** [comment]
まあいいですが。いっぺんにはむりなのは確かなので。

**Comment by akihikodaki** [comment]
1f2407c2035c39197d107771d578ea4f525b8d92: まずはページの幅。`/web/`と`/web/event/`はまだ。

**Comment by akihikodaki** [comment]
69be11251e6ca49af8e6af38092d9b4cfc6de0f8: `/web/`対応
a0b286b5933e6a2058b9fb92d7ebc2efbce030ac: `/web/event/`対応

**Comment by yumetodo** [comment]
イベントページ、3/6月に応じてCSS当ててるけど効いていないのは仕様ではないよね？
![image](https://user-images.githubusercontent.com/10869046/29751577-5ddb3a88-8b8a-11e7-9536-3cd958a5083f.png)

**Comment by yumetodo** [comment]
同じ箇所、hoverした時のCSSが当たってないのは仕様でしょうか？

**Comment by akihikodaki** [comment]
8d01e3678e5f902dcdf9a37c365f05fdcd78cf28: `/web/`の退行を解決
248cd895dbb723b872d390d40c83b0e8b6d36b60: Viewport `<meta>`タグ追加
dbe9b27f320d78212aad93094862b13c7bee0328, 1322851393d703d20e972d7f0348d5636bf22893: `/web/`で内容が`.layout_body`の外に出てしまっていた問題を解決
e258e4a3944e0d789c599ec9a837ba9df0ab1044, bd2ec1ce5d306ffc5ef448ee36640cdc5c8a80b6: clean up
c82968a8dbc1a26470e5d3fd51cdefd320b31369: `rem`を導入

**Comment by akihikodaki** [comment]
7ea0b5238de14b199f1cc6fd9c3f50e1ef362617, 96fc21d56a667b10dcc6d53ad7a095170e933e19: clean up
84a2eba0330aea265ea11df5fccadb2e85ad225c: sidebar対応
ee76dfeb1bf424d925df869b0a1c89facc494c92: 最小300pxまで対応

これにてRWD導入を完了。

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/29870259-9791b17e-8dc1-11e7-96c2-e325cb696824.png)

会場アクセスがでかくなるの納得行かねぇ・・・

**Comment by akihikodaki** [comment]
分かる
