### ISSUE TITLE
新入生向けページ/広報班: 常に#&gid=1&pid=1が末尾につく

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#85]
https://miraiken.github.io/web/for_freshman/public_relations_department.html

を開くと常にURLの末尾に`#&gid=1&pid=1`が付き、そのidの飛ぶ。

原因
https://github.com/miraiken/web/commit/d58046cc806a460489459ff6f80a39ed376c92ce

**Comment by akihikodaki** [comment]
開始時にfragmentをつけないようにするオプションなどはなかった。UXに影響はないのでクローズ。
なお、これは表示されている画像を示す。

**Comment by yumetodo** [comment]
ちょっとまった、idにhrefはったリンクを踏んだのと同じ状態なのだからつまりいきなり画面下の方の画像のところに移動するんだからどう考えてもUser experienceに影響あるだろ。

**Comment by akihikodaki** [comment]
それはURLとは違う問題だ。`id`がfragmentで指定されている場合とは異なり、それはJavaScriptが解釈する。別のissueが必要だ。
