### ISSUE TITLE
pug-linter: validateAttributeQuoteMarks

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#87]
https://github.com/pugjs/pug-lint/blob/master/docs/rules.md#validateattributequotemarks-----true

#84 で追加された

```pug
    meta(content="default-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com/ajax/libs/ https://www.google-analytics.com/",
         http-equiv='Content-Security-Policy')
```

がpug-linterの`validateAttributeQuoteMarks`というルールに引っかかり、`Invalid attribute quote mark found`と怒られている。

**Comment by akihikodaki** [comment]
c47abf85af8db744e890c4b2b32815c1765c7fbd で解決。
