### ISSUE TITLE
slideshowが動いていない

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#90]
`/index.html`にて、スライドショーが動作していない。正確には一回だけ画像が切り替わってそのまま。

**Comment by yumetodo** [comment]
`onanimationend`が

https://github.com/miraiken/web/blob/8d01e3678e5f902dcdf9a37c365f05fdcd78cf28/slideshow/index.js#L30

以外で呼ばれていない

**Comment by akihikodaki** [comment]
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36` で再現する
`Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0` で再現しない

**Comment by yumetodo** [comment]
もしかして: ブラウザによってイベント名が違う

**Comment by akihikodaki** [comment]
66554900e399be3f3fcdad32f6b7fbe3bf6b71d8 で解決。
