### ISSUE TITLE
TOPページ: background: linear-gradientが効いていない

### ISSUE THREAD

**Issue by yumetodo** [miraiken/web#92]
![image](https://user-images.githubusercontent.com/10869046/29993220-beea7748-8feb-11e7-9ba9-a37066c38394.png)

>理科が好き。だから、伝えたい。

を画像にかぶせるのはいいとして、可読性がない。

ref:
- https://github.com/miraiken/web/commit/2545a966129166e002ecb623880ecf06e3270c99

**Comment by akihikodaki** [comment]
https://github.com/miraiken/web/pull/93#issuecomment-326724678 を参照。

**Comment by yumetodo** [comment]
Firefoxで確認した、なるほど

**Comment by akihikodaki** [comment]
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36`で再現する
`Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0`で再現しない

**Comment by yumetodo** [comment]
https://stackoverflow.com/questions/1419448/hex-representation-of-a-color-with-alpha-channel

HEX styleのalpha付きRBGA指定はサポートされていない

**Comment by yumetodo** [comment]
https://github.com/miraiken/web/commit/b0112e4c9b7aebf6f28c0e76a114d14b3d006bb4
でRGBAの件は直したけど、やっぱりだめだな・・・

**Comment by akihikodaki** [comment]
e690fe84716b8de3e7f6d145f42f65a50acf7b6f で解決。

**Comment by yumetodo** [comment]
@akihikodaki なんでこれで治るのかわからねぇ、これはhtmlに書いた時のバグなのか？

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/29993710-657f8294-8ff9-11e7-986e-608893dbceb0.png)

これ見る限り

https://github.com/miraiken/web/commit/b0112e4c9b7aebf6f28c0e76a114d14b3d006bb4

とやってることは変わってないはずなのに・・・(`-webkit-`のは使われてない)

**Comment by akihikodaki** [comment]
`180deg`ってのが曲者なのか?

**Comment by yumetodo** [comment]
あ、角度指定がだめだった・・・？

**Comment by yumetodo** [comment]
いや、ちげーな

![image](https://user-images.githubusercontent.com/10869046/29993718-c584ae62-8ff9-11e7-9f02-0f8c70762cf1.png)

手元のWebpack先生の出力だと`to bottom`になってる

**Comment by akihikodaki** [comment]
分からん

**Comment by yumetodo** [comment]
Webpack  `3.5.4` -> `3.5.5`でなんかかわったか？

**Comment by yumetodo** [comment]
いや、出力違うのは

`css-loader` `0.28.4` -> `0.28.7`

のせいか。

結局cssファイルに書けばおｋってことなんだろうか・・・、納得行かねぇ。
